# Manage the labels of a GitHub repository as code.
name: Label Maker

on:
  push:
    paths:
      - .github/workflows/label-maker.yml
      - .github/labels.yml

jobs:
  label-maker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Label Maker
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false
          dry-run: false